### PR TITLE
Feature/caching s3

### PR DESCRIPTION
**Pull request by mhuguesaws**

### CODE REVIEW

**Comment by mhuguesaws** [comment]
@cgorgulla gentle ping this PR. Let me know if you want any additional changes.

**Comment by cgorgulla** [comment]
Adds support for VirtualFlow running on AWS using S3 and AWS Batch.

**Comment by cgorgulla** [comment]
@mhuguesaws Thank you very much for this extension to VirtualFlow. I created a new branch 'aws'. 

Are you able to solve the merge issues?

**Comment by mhuguesaws** [comment]
@cgorgulla I should be able to address those conflicts in the coming weeks.

**Comment by mhuguesaws** [comment]
@cgorgulla conflicts have been addressed

**Pull request closed without merging**
